task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 11 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/visdrone-dataset/VisDrone2019-DET-train/VisDrone2019-DET-train/images
    ann_file: /kaggle/working/vis_fish_finetune_dfine/annotations_VisDrone_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/visdrone-dataset/VisDrone2019-DET-val/VisDrone2019-DET-val/images
    ann_file: /kaggle/working/vis_fish_finetune_dfine/annotations_VisDrone_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction