__include__: [
  './dfine_hgnetv2_m_coco.yml',
  '../base/deim.yml'
]

output_dir: ./outputs/deim_hgnetv2_m_coco_25ep

optimizer:
  params: 
    -
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.0000125
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.000125
  betas: [0.9, 0.999]
  weight_decay: 0.0001

# Reduce training epochs
epoches: 25

# Adjust learning rate schedule
flat_epoch: 16   # 4 + 25 // 2
no_aug_epoch: 3  # reduced from 6

# Adjust data augmentation schedule
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [2, 10, 20]   # adjusted to fit within 25 epochs

  collate_fn:
    mixup_epochs: [2, 10]
    stop_epoch: 0  ## DISABLED
