__include__: [
  '../dataset/custom_detection.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
]

output_dir: ./output/dfine_hgnetv2_m_obj2custom_25ep

DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True
  pretrained: False

DFINETransformer:
  num_layers: 4
  eval_idx: -1

HybridEncoder:
  in_channels: [384, 768, 1536]
  hidden_dim: 256
  depth_mult: 0.67

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0000125
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0000125
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.000125
  betas: [0.9, 0.999]
  weight_decay: 0.000125

epochs: 25  # Adjusted for shorter training

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: [2, 10, 20]  # Adjusted for 25 epochs
  collate_fn:
    stop_epoch: 23  # Stop augmentations before final 2 epochs
    ema_restart_decay: 0.9998
    base_size_repeat: 6

ema:
  warmups: 0

lr_warmup_scheduler:
  warmup_duration: 0
